---
services:
  av:
    image: clamav/clamav:latest
    container_name: clamav
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 3G
    cpus: 2
    mem_limit: 4G
    mem_reservation: 3G
    networks:
      - backend-seatable-net

networks:
  backend-seatable-net:
    name: backend-seatable-net
