---
services:

  onlyoffice:
    image: ${SEATABLE_ONLYOFFICE_IMAGE}
    container_name: seatable-onlyoffice
    environment:
      - JWT_ENABLED=${ONLYOFFICE_JWT_ENABLED}
      - JWT_SECRET=${ONLYOFFICE_JWT_SECRET}
    volumes:
      - /opt/seatable-onlyoffice/logs:/var/log/onlyoffice
      - /opt/seatable-onlyoffice/data:/var/www/onlyoffice/Data
      - /opt/seatable-onlyoffice/lib:/var/lib/onlyoffice
      - /opt/seatable-onlyoffice:/etc/onlyoffice/documentserver
    networks:
      - seatable-net
