---
services:
  restic-backup:
    image: ${SEATABLE_RESTIC_BACKUP_IMAGE:-seatable/restic-backup:1.2.5}
    container_name: restic-backup
    restart: unless-stopped
    init: true
    volumes:
      - ${HOST_DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock
      - ${RESTIC_DATA_DIR:-/opt/restic}/data:/data
      - ${RESTIC_COMPOSE_DIR:-/opt/seatable-compose}:/data/seatable-compose:ro
      - ${SEATABLE_DATA_DIR:-/opt/seatable-server}/seatable:/data/seatable-server/seatable:ro
      - ${RESTIC_DATA_DIR:-/opt/restic}/local:/local
      - ${RESTIC_DATA_DIR:-/opt/restic}/restore:/restore
      - ${RESTIC_DATA_DIR:-/opt/restic}/cache:/root/.cache/restic
      - ${RESTIC_DATA_DIR:-/opt/restic}/logs:/var/log/
    environment:
      - TZ=${TIME_ZONE}
      - RESTIC_REPOSITORY=${RESTIC_REPOSITORY:-/local}
      - RESTIC_PASSWORD=${RESTIC_PASSWORD:?Variable is not set or empty}
      - SEATABLE_DATABASE_DUMP=${SEATABLE_DATABASE_DUMP:-true}
      - SEATABLE_DATABASE_PASSWORD=${SEATABLE_MYSQL_ROOT_PASSWORD:?Variable is not set or empty}
      - SEATABLE_BIGDATA_DUMP=${SEATABLE_BIGDATA_DUMP:-true}
      - LOG_TYPE=${LOG_TYPE:-stdout}
      - LOG_LEVEL=${RESTIC_LOG_LEVEL:-INFO}
    networks:
      - backend-seatable-net

networks:
  backend-seatable-net:
    external: true
