---
services:
  restic-backup:
    image: ${SEATABLE_RESTIC_BACKUP_IMAGE:-seatable/restic-backup:1.1.0}
    container_name: restic-backup
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/seatable-compose:/data/seatable-compose:ro
      - /opt/seatable-server/seatable:/data/seatable-server/seatable:ro
      - /opt/restic/local:/local
      - /opt/restic/restore:/restore
      - /opt/restic/cache:/root/.cache/restic
      - /opt/restic/hooks:/hooks:ro
      - /opt/restic/logs:/var/log/
      - /opt/restic/mount:/mnt/mount:shared # needed for "restic mount" / :shared volume to see the content of mounted fuse filesystem from host
    devices:
      - /dev/fuse # needed for "restic mount" / access to the host filesystem
    cap_add:
      - SYS_ADMIN # needed for "restic mount" / grants sysadmin capabilities
    security_opt:
      - apparmor:unconfined # needed for "restic mount" / disable apparmor
    environment:
      - RESTIC_REPOSITORY=${RESTIC_REPOSITORY:-/local}
      - RESTIC_PASSWORD=${RESTIC_PASSWORD:?Variable is not set or empty}
      - RESTIC_TAG=${SEATABLE_SERVER_HOSTNAME:-seatable}
      - BACKUP_CRON=${BACKUP_CRON:-15 2 * * *} # Start backup always at 2:15 am.
      - CHECK_CRON=${CHECK_CRON:-45 3 \* \* 6} # Start check every sunday at 3:45am
      - RESTIC_DATA_SUBSET=${RESTIC_DATA_SUBSET:-1G} # Download max 1G of data from backup and check the data integrity
      - RESTIC_FORGET_ARGS=${RESTIC_FORGET_ARGS:- --prune --keep-daily 6 --keep-weekly 4 --keep-monthly 6}
      - RESTIC_JOB_ARGS=${RESTIC_JOB_ARGS:- --exclude=/data/seatable-server/seatable/logs --exclude=/data/seatable-server/seatable/db-data --exclude-if-present .exclude_from_backup}
      - SEATABLE_DATABASE_DUMP=${SEATABLE_DATABASE_DUMP:-true}
      - SEATABLE_DATABASE_HOST=${SEATABLE_DATABASE_HOST:-mariadb}
      - SEATABLE_DATABASE_USER=${SEATABLE_DATABASE_USER:-root}
      - SEATABLE_DATABASE_PASSWORD=${SEATABLE_MYSQL_ROOT_PASSWORD:?Variable is not set or empty}
      - SEATABLE_BIGDATA_DUMP=${SEATABLE_BIGDATA_DUMP:-true}
      - SEATABLE_BIGDATA_HOST=${SEATABLE_BIGDATA_HOST:-seatable-server}
      - HEALTHCHECK_URL=${HEALTHCHECK_URL}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY_ID=${AWS_SECRET_ACCESS_KEY_ID}
      - B2_ACCOUNT_ID=${B2_ACCOUNT_ID}
      - B2_ACCOUNT_KEY=${B2_ACCOUNT_KEY}
