---
services:
  restic-backup:
    image: ${SEATABLE_RESTIC_BACKUP_IMAGE:-seatable/restic-backup:1.2.5}
    container_name: restic-backup
    restart: unless-stopped
    init: true
    volumes:
      - ${HOST_DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock
      - ${RESTIC_DATA_DIR:-/opt/restic}/data:/data
      - ${RESTIC_COMPOSE_DIR:-/opt/seatable-compose}:/data/seatable-compose:ro
      - ${SEATABLE_DATA_DIR:-/opt/seatable-server}/seatable:/data/seatable-server/seatable:ro
      - ${RESTIC_DATA_DIR:-/opt/restic}/local:/local
      - ${RESTIC_DATA_DIR:-/opt/restic}/restore:/restore
      - ${RESTIC_DATA_DIR:-/opt/restic}/cache:/root/.cache/restic
      - ${RESTIC_DATA_DIR:-/opt/restic}/logs:/var/log/
    environment:
      - TZ=${TIME_ZONE}
      - RESTIC_REPOSITORY=${RESTIC_REPOSITORY:-/local}
      - RESTIC_PASSWORD=${RESTIC_PASSWORD:?Variable is not set or empty}
      - DATABASE_DUMP=${SEATABLE_DATABASE_DUMP:-true}
      - DATABASE_HOST=${DATABASE_HOST:-mariadb}
      - DATABASE_PASSWORD=${SEATABLE_MYSQL_ROOT_PASSWORD:?Variable is not set or empty}
      - DATABASE_DUMP_COMPRESSION=${DATABASE_DUMP_COMPRESSION:-false}
      - SEATABLE_BIGDATA_DUMP=${SEATABLE_BIGDATA_DUMP:-true}
      - SEATABLE_BIGDATA_HOST=${SEATABLE_BIGDATA_HOST:-seatable-server}
      - LOG_TYPE=${LOG_TYPE:-stdout}
      - LOG_LEVEL=${RESTIC_LOG_LEVEL:-INFO}
#      - TZ=${TIME_ZONE}
#      - RESTIC_REPOSITORY=${RESTIC_REPOSITORY:-/local}
#      - RESTIC_PASSWORD=${RESTIC_PASSWORD:?Variable is not set or empty}
#      - RESTIC_TAG=${SEATABLE_SERVER_HOSTNAME:-seatable}
#      - BACKUP_CRON=${BACKUP_CRON:-15 2 * * *} # Start backup always at 2:15 am.
#      - CHECK_CRON=${CHECK_CRON:-45 3 * * 6} # Start check every sunday at 3:45am
#      - RESTIC_DATA_SUBSET=${RESTIC_DATA_SUBSET:-1G} # Download max 1G of data from backup and check the data integrity
#      - RESTIC_FORGET_ARGS=${RESTIC_FORGET_ARGS:- --prune --keep-daily 6 --keep-weekly 3 --keep-monthly 3}
#      - RESTIC_JOB_ARGS=${RESTIC_JOB_ARGS:- --exclude=/data/seatable-server/seatable/logs --exclude=/data/seatable-server/seatable/db-data --exclude-if-present .exclude_from_backup}
#      - LOG_TYPE=${LOG_TYPE:-stdout}
#      - LOG_LEVEL=${LOG_LEVEL:-INFO}
#      - DATABASE_DUMP=${SEATABLE_DATABASE_DUMP:-true}
#      - DATABASE_HOST=${DATABASE_HOST:-mariadb}
#      - DATABASE_PASSWORD=${SEATABLE_MYSQL_ROOT_PASSWORD:?Variable is not set or empty}
#      - DATABASE_DUMP_COMPRESSION=${DATABASE_DUMP_COMPRESSION:-false}
#      - SEATABLE_BIGDATA_DUMP=${SEATABLE_BIGDATA_DUMP:-true}
#      - SEATABLE_BIGDATA_HOST=${SEATABLE_BIGDATA_HOST:-seatable-server}
#      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-}
#      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
#      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
#      - HEALTHCHECK_URL=${HEALTHCHECK_URL:-}   
    networks:
      - backend-seatable-net

#networks:
#  backend-seatable-net:
#    external: true
