---
services:
  seatable-python-scheduler:
    image: ${SEATABLE_SCHEDULER_IMAGE:-seatable/seatable-python-scheduler:4.2.9}
    restart: unless-stopped
    container_name: seatable-python-scheduler
    environment:
      - TIME_ZONE=${TIME_ZONE}
      - DB_HOST=${SEATABLE_MYSQL_HOST:-seatable-db}
      - DB_ROOT_PASSWD=${SEATABLE_MYSQL_ROOT_PASSWORD:?Variable is not set or empty}
      - PYTHON_SCHEDULER_AUTH_TOKEN=${PYTHON_SCHEDULER_AUTH_TOKEN}
      - SEATABLE_SERVER_URL=${SEATABLE_SERVER_URL}
      - PYTHON_STARTER_URL=${PYTHON_STARTER_URL:-http://seatable-python-starter:8080}
      - PYTHON_SCHEDULER_LOG_LEVEL=${PYTHON_SCHEDULER_LOG_LEVEL:-WARNING}
      - DELETE_LOG_DAYS=${DELETE_LOG_DAYS:-30}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - frontend-net
      - backend-scheduler-net
      - backend-seatable-net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pgrep -f 'python3 scheduler.py' && pgrep -f 'python3 flask_server.py'",
        ]
      interval: 20s
      retries: 3
      start_period: 20s
      timeout: 10s

  seatable-python-starter:
    image: ${SEATABLE_STARTER_IMAGE:-seatable/seatable-python-starter:4.2.9}
    restart: unless-stopped
    container_name: seatable-python-starter
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${PYTHON_TRANSFER_DIRECTORY_PATH:-/tmp}:${PYTHON_TRANSFER_DIRECTORY_PATH:-/tmp}"
    environment:
      - PYTHON_SCHEDULER_URL=${PYTHON_SCHEDULER_URL}
      - PYTHON_TRANSFER_DIRECTORY=${PYTHON_TRANSFER_DIRECTORY_PATH:-/tmp}
      - PYTHON_RUNNER_IMAGE=${PYTHON_RUNNER_IMAGE:-seatable/seatable-python-runner:4.2.9}
      - PYTHON_STARTER_LOG_LEVEL=${PYTHON_STARTER_LOG_LEVEL:-WARNING}
    networks:
      - backend-scheduler-net

  seatable-python-runner:
    image: ${SEATABLE_RUNNER_IMAGE:-seatable/seatable-python-runner:4.2.9}
    restart: unless-stopped
    container_name: seatable-python-runner
    networks:
      - backend-scheduler-net

networks:
  frontend-net:
    name: frontend-net
  backend-scheduler-net:
    name: backend-scheduler-net
