---
services:

# Webserver / Reverse-proxy
# Volume :/data/ is for acme and :/data/certs/ for custom certificates
  caddy:
    image: ${SEATABLE_CADDY_IMAGE:-lucaslorentz/caddy-docker-proxy:2.8.8-alpine}
    restart: unless-stopped
    container_name: seatable-caddy
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=frontend-net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/opt/seatable-caddy:/data"
    networks:
      - frontend-net

networks:
  frontend-net:
    name: frontend-net
