name: Release on tag push

on:
  push:
    tags:
      - "release-v*.*.*"

jobs:

  init-vars:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_github_ref_version.outputs.version }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name : Validate github.ref format in case of others triggers used
        id: validate_github_ref
        run: |
          if [[ ! "${{ github.ref }}" =~ ^refs/tags/release-v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid github.ref format"
            exit 1
          fi
      - name: Extract version from github.ref
        id: extract_github_ref_version
        run: echo "version=$(echo ${{ github.ref }} | awk -F/ '{print $3}' | awk -Fv '{print $2}')" >> $GITHUB_OUTPUT

  validate-yml:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: vaildate yml files
        uses: mikefarah/yq@master
        with:
          cmd: yq 'true' compose/*.yml

  release-on-tag-push:
    runs-on: ubuntu-latest
    needs:
      - init-vars
      - validate-yml
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Compress content of compose folder
        run: tar -czvf seatable-compose.tar.gz -C compose/ .
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.init-vars.outputs.version }}
          files: |
            seatable-compose.tar.gz
